API_HOST_URL: 'http://localhost:8000'
SSO_URL: 'http://localhost:8000'
SSO_FINISHED_URL:  'http://localhost:8000'
ENVIRONMENT_DISPLAY_NAME: 'Localhost'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
OAUTH_CLIENT_ID: ''

PRE_LOGIN_EXPERIENCE_ENABLED: false
REGISTRATION_ENABLED: false

APPLE_SIGNIN: true

GOOGLE:
  ENABLED: true
  GOOGLE_PLUS_KEY: 'string'
  CLIENT_ID: 'string'

# SSO_BUTTON_TITLE:
#     ar: "الدخول عبر SSO"
#     en: "Sign in with SSO"



UI_COMPONENTS:
    COURSE_UNIT_PROGRESS_ENABLED: false
    COURSE_NESTED_LIST_ENABLED: false
    LOGIN_REGISTRATION_ENABLED: true
    SAML_SSO_LOGIN_ENABLED: false
    SAML_SSO_DEFAULT_LOGIN_BUTTON: false
