API_HOST_URL: 'https://courses.goamazing.org'
SSO_URL: 'https://courses.goamazing.org'
SSO_FINISHED_URL:  'https://courses.goamazing.org'
ENVIRONMENT_DISPLAY_NAME: 'https://courses.goamazing.org'
FEEDBACK_EMAIL_ADDRESS: 'contact@goamazing.org'
OAUTH_CLIENT_ID: 'UPBKHIhpNqhqNknEe74tQcQoG9BC8Lst1qYwQal8'

SSO_BUTTON_TITLE:
    ar: "الدخول عبر SSO"
    en: "Sign in with SSO"

PRE_LOGIN_EXPERIENCE_ENABLED: false
REGISTRATION_ENABLED: false

UI_COMPONENTS:
    COURSE_UNIT_PROGRESS_ENABLED: false
    COURSE_NESTED_LIST_ENABLED: false
    LOGIN_REGISTRATION_ENABLED: true
    SAML_SSO_LOGIN_ENABLED: false
    SAML_SSO_DEFAULT_LOGIN_BUTTON: false
